import random
from pyrogram import filters
from ShrutiMusic import app

TRUTHS = [
    "KYA TUMNE KABHI KISI KO GALAT NAAM SE BULAYA HAI? 😂",
"AGAR TUM EK DIN KE LIYE OPPOSITE GENDER BAN JAO TO SABSE PEHLE KYA KAROGE? 😜",
"KYA TUMNE KABHI EX KO FAKE ACCOUNT SE STALK KIYA HAI? 👀",
"GROUP ME SABSE ZYADA ATTITUDE KISKA HAI? 😏",
"KIS MEMBER KE SAATH EK DIN GHOOMNA PASAND KAROGE? 🚗",
"KYA TUMNE KABHI EXAM ME CHEATING KI HAI? 🤭",
"TUMHARI SABSE CRINGE CHAT KISKE SAATH HUI THI? 😂",
"AGAR TUMHE 24 GHANTE KE LIYE INVISIBLE POWER MIL JAYE TO KYA KAROGE? 👻",
"KYA TUMNE KABHI KISI KO 'SEEN' KARKE IGNORE KIYA HAI? 📱",
"GROUP ME SABSE CUTE DP KISKI HAI? 😍",
"KIS CELEBRITY PAR TUMHARA CRUSH HAI? 🌟",
"KYA TUMNE KABHI APNE BEST FRIEND SE JHOOTH BOLA HAI? 😅",
"TUMHARA SABSE SHARMAANE WALA MOMENT KYA THA? 🙈",
"AGAR TUM TIME TRAVEL KAR SAKO TO KIS SAAL ME JAOGE? ⏳",
"KYA TUMNE KABHI LOVE LETTER LIKHA HAI? 💌",
"TUM SABSE ZYADA KIS BAAT SE DARTE HO? 😨",
"GROUP ME SABSE ZYADA OVERSMART KAUN HAI? 🤓",
"AGAR TUMHE 3 WISHES MIL JAYE TO KYA MAANGOGE? ✨",
"KYA TUMNE KABHI KISI KO GALTI SE 'LOVE YOU' BHEJ DIYA HAI? 😂",
"TUMHARI FAVOURITE CHILDHOOD MEMORY KYA HAI? 🧸",
"KYA TUMNE KABHI BINA BATAYE KISI KA KHANA KHAYA HAI? 🍕",
"GROUP ME SABSE SWEET PERSON KAUN HAI? 💖",
"KYA TUMNE KABHI KISI PAR JEALOUS FEEL KIYA HAI? 😏",
"AGAR TUM SUPERHERO BAN JAO TO TUMHARI POWER KYA HOGI? 🦸",
"KYA TUM KABHI POLICE SE BACHE HO? 🚔😂",
"TUMHARA SABSE WEIRD SEARCH HISTORY KYA HAI? 🔍",
"GROUP ME KISKO SABSE PEHLE REPLY DETE HO? 📲",
"KYA TUMNE KABHI APNI PHOTO PAR KHUD HI LIKE KIYA HAI? 🤣",
"AGAR TUMHE CHAND PAR JANE KA MAUKA MILE TO JAOGE? 🌙",
"TUMHARA SABSE BADA REGRET KYA HAI? 🤔",
]

DARES = [
"AGLE 5 MESSAGES SIRF EMOJIS ME REPLY KARO 😂",
"GROUP KE KISI EK MEMBER KI DIL SE TAREEF KARO ❤️",
"APNI FAVOURITE SELFIE KA EMOJI VERSION BANAO 🤣",
"KISI EK MEMBER KO EK FUNNY NICKNAME DO 😜",
"AGLE 3 MESSAGES ME HAR LINE KE END ME '😂' LAGAO.",
"EK SHAYARI SUNAO JO TUMHE YAAD HO ❤️",
"GROUP ME LIKHO: 'AAJ SABKO CHAI ☕ MERI TARAF SE!' 😂",
"APNA FAVOURITE SONG BATAO AUR EK LINE GAO 🎤",
"AGLE 2 MINUTE TAK CAPS LOCK ME HI CHAT KARO 😆",
"KISI MEMBER KO 🌹 EMOJI BHEJO AUR BOLO 'JUST FOR FUN 😂'",
"EK RANDOM FACT SHARE KARO JO KAM LOG JAANTE HAIN 🤓",
"APNE PHONE KI LAST APP KA NAAM BATAO 📱",
"GROUP ME SABKO 'GOOD LUCK ❤️' WISH KARO.",
"EK JOKE SUNAO AGAR KOI NA HASE TO DUSRA SUNAO 🤣",
"APNA FAVOURITE FOOD BATAO AUR SABKO TREAT KA PROMISE KARO 🍕",
"AGLE 5 MESSAGES ME SIRF GIF YA STICKER USE KARO 😜",
"GROUP KE SABSE FUNNY MEMBER KO TAG KARKE 😂 BHEJO.",
"KISI EK MEMBER KO FRIENDLY ROAST KARO 😆",
"LIKHO: 'MAIN GROUP KA OFFICIAL COMEDIAN HOON 🤡'",
"10 TAK ULTI GINTI LIKHO BINA GALTI KIYE 🔢",
"APNI FAVOURITE MOVIE KA DIALOGUE LIKHO 🎬",
"KISI EK MEMBER KO FRIENDLY 'THANK YOU ❤️' BHEJO.",
"AGLE 3 MESSAGES ME SIRF YES YA NO ME REPLY KARO 😂",
"GROUP ME APNA SABSE WEIRD HABIT BATAO 🤪",
"EK TONGUE TWISTER LIKHO AUR SABKO TRY KARNE BOLO 😅",
"AGLE 2 MINUTE TAK HAR MESSAGE KI SHURUAT 'JI HUZOOR' SE KARO 🤣",
"KISI MEMBER KO EK CUTE EMOJI COMBO BHEJO 🥹❤️",
"APNA FAVOURITE CARTOON CHARACTER BATAO 🧸",
"GROUP ME EK MOTIVATIONAL LINE LIKHO 💪",
"LIKHO: 'AAJ MAIN SABKA FAN HOON 😎'",
"KISI EK MEMBER KO BOLO 'AAP TOH VIP HO 😏'",
"EK HEART ❤️ AUR EK FIRE 🔥 EMOJI KE SAATH MESSAGE BHEJO.",
"AGLE MESSAGE ME APNE NAAM KE SAATH 😎 EMOJI LAGAO.",
"KISI EK MEMBER KO BOLO 'AAJ TUMHARI DP MAST LAG RAHI HAI 😄'",
"GROUP ME EK PUZZLE PUCHO 🧩",
"ISE I LOVE YOU BOLO @OYE_BABYY 😁",
"AGLE 5 MESSAGES ME KOI PUNCTUATION MAT USE KARO 😜",
"KISI EK MEMBER KO VIRTUAL HIGH-FIVE ✋ DO.",
"LIKHO: 'MISSION COMPLETE 😎' BINA KOI CONTEXT DIYE 😂",
"GROUP ME APNI FAVOURITE HOLIDAY DESTINATION BATAO 🌴"
]

@app.on_message(filters.command("truth"))
def get_truth(client, message):
    question = random.choice(TRUTHS)
    message.reply_text(
        f"🎲 **TRUTH QUESTION**\n\n{question}"
    )

@app.on_message(filters.command("dare"))
def get_dare(client, message):
    question = random.choice(DARES)
    message.reply_text(
        f"🔥 **DARE CHALLENGE**\n\n{question}"
    )

__MODULE__ = "Truth Or Dare"

__HELP__ = """
🎲 Truth Or Dare

/truth - Get a random truth question
/dare - Get a random dare challenge
"""